tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "d12frosted/emacs-plus"
tap "hashicorp/tap"
tap "homebrew/cask-fonts"
tap "mike-engel/jwt-cli"

cask "1password"
cask "lastpass"
cask "keybase"
cask "firefox"
cask "iterm2"
cask "nextcloud"
cask "visual-studio-code"
cask "google-cloud-sdk"
cask "alfred"
cask "docker"
cask "font-hack-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-source-code-pro-for-powerline"


# cask "zoomus"
# cask "slack"



brew "ack"
brew "bat"
brew "curl"
brew "fzf"
brew "helm"
brew "helmfile"
brew "minikube", link: false
brew "pandoc"
brew "the_silver_searcher"
brew "tmux"
brew "zsh"
brew "zsh-completions"
brew "z"
brew "watch"
brew "wget"
brew "consul"
brew "pulumi"
brew "pwgen"
brew "macvim"
brew "krew"
brew "kubectx"
brew "kustomize"
brew "jq"
brew "keychain"
brew "d12frosted/emacs-plus/emacs-plus@27"
brew "git"
brew "ripgrep"
brew "fd"
brew "coreutils"
brew "tree"
brew "tfenv"
# brew "terragrunt"
brew "gnupg"
brew "git-crypt"
brew "skaffold"
brew "krew"
brew "pngpaste"
# brew "kubetail"
brew "stern"
brew "ncdu"
brew "svn"
brew "vault"
brew "hugo"
brew "ispell"
brew "terraform_landscape"
brew "jwt-cli"
brew "pinentry-mac"
brew "editorconfig"
brew "cmake"
brew "shellcheck"
brew "nmap"
brew "ansible"
