#+TITLE: Justyn's Doom Config
#+STARTUP: folded

* TOC :TOC_3_gh:
- [[#references][References]]
  - [[#example-doom-literate-configs][Example Doom literate configs]]
  - [[#doomcasts][Doomcasts]]
- [[#things-i-need-to-work-on][Things I need to work on]]
- [[#doom-specific-config][Doom-specific Config]]
  - [[#doom-initel][Doom init.el]]
  - [[#default-doom-configel][Default Doom config.el]]
  - [[#default-packagesel][Default packages.el]]
  - [[#open-which-key-popup-quicker][Open which-key popup quicker]]
  - [[#keybinding-to-sync-doom-config][Keybinding to sync doom config]]
- [[#packages][Packages]]
  - [[#powerthesaurus][Powerthesaurus]]
  - [[#string-inflection][string-inflection]]
- [[#local-config][Local config]]
  - [[#local-machine-overrides][Local machine overrides]]
  - [[#customizations][Customizations]]
- [[#org-mode][Org Mode]]
  - [[#general][General]]
  - [[#org-directories][Org Directories]]
  - [[#org-structure-template-shortcuts][Org Structure Template shortcuts]]
  - [[#org-agenda][Org Agenda]]
    - [[#general-settings][General settings]]
    - [[#org-todo-keywords][Org todo keywords]]
  - [[#org-capture-templates][Org Capture Templates]]
  - [[#org-crypt][org-crypt]]
- [[#keybindings][Keybindings]]
  - [[#useful-keybinding-reminders][Useful keybinding reminders]]
    - [[#convert-lists-between-orderednumbereunordered][Convert Lists between ordered/numbere/unordered]]
    - [[#org-outline-navigation][Org outline navigation]]
  - [[#keybindings-from-spacemacs][Keybindings from Spacemacs]]
  - [[#misc-keybindings][Misc Keybindings]]
  - [[#navigation][Navigation]]
- [[#display][Display]]
  - [[#window-size-and-position][Window Size and Position]]
  - [[#font-and-font-sizing][Font and font sizing]]
  - [[#theme][Theme]]
  - [[#move-to-new-split-windows][Move to new split windows]]
  - [[#indent-guides][Indent guides]]
  - [[#fix-flickering][Fix flickering]]
  - [[#better-windowframe-titles][Better window/frame titles]]
- [[#file-management][File management]]
  - [[#send-deleted-files-to-trash][Send deleted files to trash]]
- [[#editing][Editing]]
  - [[#general-editing-defaults][General Editing defaults]]
  - [[#tabs-vs-spaces][Tabs vs Spaces]]
  - [[#unicode-elipsis][Unicode elipsis]]
  - [[#markdown-mode][Markdown Mode]]
  - [[#terraform][Terraform]]
  - [[#corfu-completion][Corfu Completion]]
- [[#version-control][Version Control]]
  - [[#magit][magit]]
  - [[#treemacs-magit][treemacs-magit]]
- [[#projectile][Projectile]]
- [[#ssh-and-gpg-agent][SSH and GPG Agent]]
- [[#tramp][Tramp]]
- [[#tags][Tags]]
- [[#evil-snipe][evil-snipe]]
- [[#backups-and-history][Backups and history]]
  - [[#backups-and-auto-save][Backups and auto-save]]
  - [[#save-place][Save place]]
- [[#hydra-paste][Hydra Paste]]
- [[#avy][Avy]]
- [[#yasnippet][yasnippet]]

* References

** Example Doom literate configs

Found and referenced several of these while working on updating my config.

- https://github.com/martinbaillie/dotfiles/blob/master/config/emacs/config.org
- https://github.com/murphytalk/doom.d/blob/master/README.org
- https://github.com/nmartin84/.doom.d/blob/master/config.org
- https://gitlab.com/justinekizhak/dotfiles/blob/master/emacs/doom.d/config.org
- https://noelwelsh.com/posts/2019-01-10-doom-emacs.html
- https://www.gtrun.org/custom/init.html
- https://www.reddit.com/r/emacs/comments/empzmz/doom_emacs_literate_config/
- https://tecosaur.github.io/emacs-config/config.html (really detailed and includes a lot of explanations/background)

** Doomcasts

These videos are a good intro to doom emacs and some of the common features.
https://www.youtube.com/watch?v=ywRExNOyybY&list=PLhXZp00uXBk4np17N39WvB80zgxlZfVwj&index=6

* Things I need to work on

Stuff I need to figure out for doom-emacs config

- [X] smart paste - In spacemacs, I can press =p= and then =C-j= and =C-k= to cycle between different kill rings
- [ ] Try [[https://github.com/bastibe/annotate.el][annotate mode]] like in [[https://gitlab.com/justinekizhak/dotfiles/blob/master/emacs/doom.d/config.org][this config]]
- [ ] Use gpg for all of my org files? (Wouldnt be able to access on android anymore though)
- [ ] Make more of a cheatsheet/reference for common keybindings
- [X] Setup deft?
- [X] Setup org-clock and my helper functions for it
- [ ] Setup and test lsp for terraform and python
- [ ] ctrl+enter doesn't work to add to lists in a terminal
- [ ] make =SPC /= work for searching project
- [ ] org-rifle
- [ ] better keybindings for moving between windows/panes
- [X] my =~/.ctags= config isn't getting picked up
- [ ] I think ivy is used for the minibuffer completion.  It's not as fuzzy as helm (I think?) was, so searching for files in a project is more annoying
- [X] get lsp working for terraform
- [X] clocking into a task doesn't clock out of the previous task anymore, leading to duplicate time
- [ ] How to get org-agenda to show overlapping times?
- [ ] Show clocked-in tasks in the daily agenda?
- [ ] Figure out how to get logged hours to show up in the agenda by default
- [ ] yasnippet or something else to insert current timestamp into buffer (I used to expand =ts= before)
- [ ] Update my doom config from 2021 to 2026 so I can start u sing it again

* Doom-specific Config

Config related to Doom itself, or packages I probably wouldn't use if Doom wasn't using it.  This should also be the first section of my config and get added to the top of the file.

** Doom init.el

To update this, press =C-c '= in the below block and also open init.el from doom, then use =ediff-buffers= to open ediff for the two.

#+BEGIN_SRC emacs-lisp :tangle init.el
;;; $DOOMDIR/init.el -*- lexical-binding: t; -*-

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE: Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;   documentation. There you'll find a link to Doom's Module Index where all of
;;   our modules are listed, including what flags they support.

;; NOTE: Move your cursor over a module's name (or its flags) and press 'K' (or
;;   'C-c c k' for non-vim users) to view its documentation. This works on flags
;;   as well (those symbols that start with a plus).
;;
;;   Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;   directory (for easy access to its source code).

(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       ;;company           ; the ultimate code completion backend
       (corfu +orderless)  ; complete with cap(f), cape and a flying feather!
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future

       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       dashboard         ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;indent-guides     ; highlighted indent columns
       ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;smooth-scroll     ; So smooth you won't believe it's not butter
       tabs              ; a tab bar for Emacs
       treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       ;;workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       format
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       (whitespace +guess +trim)  ; a butler for your whitespace
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ;;eww             ; the internet is gross
       ;;ibuffer         ; interactive buffer management
       tramp             ; remote files at your arthritic fingertips
       (undo +tree)      ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       ;; vterm             ; almost the best terminal emulation in Emacs
       ghostel           ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;collab            ; buffers with friends
       ;;debugger          ; stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       lookup              ; navigate your code and its documentation
       ;;llm               ; when I said you needed friends, I didn't mean...
       ;;(lsp +eglot)      ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;tree-sitter       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if (featurep :system 'macos) macos)  ; improve compatibility with macOS
       tty               ; improve the terminal Emacs experience

       :lang
       ;;ada               ; In strong typing we (blindly) trust
       ;;(agda +local)     ; types of types of types of types...
       beancount         ; mind the GAAP
       ;;(cc +lsp)         ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       json              ; At least it ain't XML
       ;;janet             ; Fun fact: Janet is me!
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       ;;odin              ; C, minus its footguns
       (org +dragndrop +pandoc)               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;graphviz          ; diagrams for confusing yourself even more
       ;;purescript        ; javascript, but functional
       (python +lsp)       ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scad              ; trust the preview, regret the render
       ;;scala             ; java, but good
       ;;scheme            ; a fully conniving family of lisps
       (sh +lsp)           ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       yaml              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       ;;everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader

       :config
       literate
       (default +bindings +smartparens))
#+END_SRC

** Default Doom config.el

This is what came in config.el when it first got generated.  I've moved some of it into other sections where it makes sense.  Eventually I'll move everything out.

#+BEGIN_SRC emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Justyn Shull"
      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)


;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)


;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

#+END_SRC
** Default packages.el

Empty packages.el file, but with the default comments.

#+BEGIN_SRC emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/raxod502/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see raxod502/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)
#+END_SRC

** Open which-key popup quicker

#+BEGIN_SRC emacs-lisp
(setq which-key-idle-delay 0.25)
#+END_SRC
** Keybinding to sync doom config

First, functions to run doom sync/build.  They use =compile= (async, so Emacs doesn't
hang) in a =*doom*= buffer.  Doom already puts =ansi-color-compilation-filter= on
=compilation-filter-hook=, so the CLI's ANSI colors render instead of showing as raw
escape codes.

#+BEGIN_SRC emacs-lisp
(defun justyn/doom-compile (command)
  "Run doom COMMAND in an async compilation buffer (with ANSI colors)."
  (let ((default-directory doom-user-dir)
        (compilation-buffer-name-function (lambda (&rest _) "*doom*")))
    (compile command)))

(defun justyn/doom-sync ()
  "Run `doom sync'."
  (interactive)
  (justyn/doom-compile "doom sync"))

(defun justyn/doom-sync-and-build ()
  "Run `doom sync && doom build'."
  (interactive)
  (justyn/doom-compile "doom sync && doom build"))
#+END_SRC

And a keybinding for =SPC j d s=.  I should probably shorten this to something else, but I should also decide whether I want to try and reserve =SPC j= for myself or figure out a better prefix.

#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix ("j" . "justyn")
               (:prefix ("d" . "doom")
                        :desc "Doom sync" "s" #'justyn/doom-sync
                        :desc "Doom sync/build" "S" #'justyn/doom-sync-and-build)))
#+END_SRC
* Packages

I think I can split this up into other sections throughout the file, but I'm just leaving it here for now.

#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! treemacs-magit)
(package! powerthesaurus)
(package! string-inflection)
(package! keychain-environment)
(package! hydra)        ; for the hydra-paste transient (the ui/hydra module was removed)
#+END_SRC
** Powerthesaurus

[[https://github.com/SavchenkoValeriy/emacs-powerthesaurus][Powerthesaurus]], use =SPC j a p= to look up a synonym for the word at the cursor.

(The apps live under =SPC j a= rather than =SPC a=, because the vertico module now binds
=SPC a= to =embark-act=.)

#+BEGIN_SRC elisp
(use-package! powerthesaurus
  :defer t)
(map! :leader
      (:prefix ("j" . "justyn")
               (:prefix ("a" . "applications")
                        :desc "Use powerthesaurus to fetch better word" "p" #'powerthesaurus-lookup-dwim)))
#+END_SRC
** string-inflection

[[https://github.com/akicho8/string-inflection][string-inflection]], use =SPC j a c= to cycle a word like this:
emacs_lisp => EMACS_LISP => EmacsLisp => emacsLisp => emacs-lisp => Emacs_Lisp => emacs_lisp

#+BEGIN_SRC elisp
(use-package! string-inflection
  :defer t)
(map! :leader
      (:prefix ("j" . "justyn")
               (:prefix ("a" . "applications")
                        :desc "Cycle through string case using String-inflection" "c" #'string-inflection-all-cycle)))
#+END_SRC
* Local config
** Local machine overrides

Similar how I use =.bashrc.local=, this will load a =~/.doom.local.el= if it exists.  I use this to set personal/private things that either change depending on the machine I'm on or that I just don't want to commit to git.

#+BEGIN_SRC emacs-lisp
(if (file-exists-p "~/.doom.local.el")
    (load-file "~/.doom.local.el"))
#+END_SRC

** Customizations

Customizations made via emacs customization interface should go to a separate file instead of init.el which gets rewritten when this file is saved.

#+begin_src emacs-lisp
(setq-default custom-file (expand-file-name ".custom.el" doom-user-dir))
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src

* Org Mode

A lean org setup: directories, todo keywords, a couple of capture templates, and the
default agenda.  The heavier work-time-tracking machinery (clocking, worklog/meeting
captures, super-agenda, journal, Jira export) was removed in 2026-07 and lives in
[[file:config.org_archive][config.org_archive]] if I want it back.

** General

General settings that I don't know how to categorize yet.

#+BEGIN_SRC emacs-lisp
(after! org
  ;; Default Column View
  (setq org-columns-default-format "%5TODO %30ITEM(Task) %10Effort(Effort){:} %10CLOCKSUM(Clocked) %3PRIORITY(PRI) %TAGS")

  ;; Enable speed commands for single-key commands at the beginning of headers.  ? for help  TODO: I don't really know what these do
  (setq org-use-speed-commands t)
  ;; Prettier code blocks
  (setq org-src-fontify-natively t)
  ;; Hide code blocks by default in org-mode
  (setq org-hide-block-startup t)

  ;; Open .org files as folded by default
  (setq org-startup-folded 'overview)
  )
#+END_SRC

#+RESULTS:
: overview

** Org Directories

Set org-directory.

#+BEGIN_SRC emacs-lisp
;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads, so don't use after!
(setq org-directory "~/org/")
#+END_SRC
** Org Structure Template shortcuts

Access these by using =C-c C-,= and then using the shortcut for each one.  It adds the =+BEGIN_SRC= block for whichever item you choose.

#+BEGIN_SRC elisp
;; Shortcuts for org-structure templates (the +BEGIN_SRC type blocks)
;; This can be accessed by pressing C-c C-,
(after! org
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("sh" . "src bash"))
  (add-to-list 'org-structure-template-alist '("y" . "src yaml"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  )
#+END_SRC

** Org Agenda
*** General settings

#+BEGIN_SRC elisp
(after! org
  (setq org-agenda-files (quote ("~/org/" "~/org/journal/")))
  (setq org-refile-targets '((org-agenda-files . (:maxlevel . 3))))

  ;; Disable tag inheritence to speed up agenda rendering
  (setq org-agenda-use-tag-inheritance nil)
  ;; Disable dim blocked tasks to speed up agenda rendering
  (setq org-agenda-dim-blocked-tasks nil)
  ;; Don't prepare agenda buffers on startup
  (setq org-agenda-inhibit-startup t)
  ;; Don't kill agenda buffers, just hide them
  (setq org-agenda-sticky t)
  ;; Disable processing some org drawer properties to speed up the agenda rendering
  (setq org-agenda-ignore-drawer-properties '(effort appt category))
  ;; TODO: Do I want this?  It logs status changes into a LOGBOOK drawer instead of just as a list
  (setq org-log-into-drawer t)
  ;; Hide things that are done
  (setq org-agenda-skip-scheduled-if-done t
   org-agenda-skip-deadline-if-done t)
  ;; org-enforce-todo-checkbox-dependencies t
  ;; org-enforce-todo-dependencies t
  )
#+END_SRC
*** Org todo keywords

This isn't really org-agenda specific, but the agenda view is where I'd see this the most really.

#+BEGIN_SRC elisp
;; Keywords to use by default in .org files
(after! org
    (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "IN-PROGRESS(i!)" "|" "DONE(d!)")
            (sequence "WAITING(w@/!)" "BLOCKED(b@/!)" "|" "CANCELLED(c@/!)")
            (sequence "[ ](T)" "[-](P)" "[?](M)" "|" "[X](D)"))))
#+END_SRC
** Org Capture Templates

#+BEGIN_SRC elisp
(after! org
  (setq org-capture-templates
        '(("t" "Todo" entry (file+headline "~/org/TODO.org" "Tasks")
           "* TODO %?\nCREATED: %U\n%i\n%a")
          ("r" "Read Later" entry (file+headline "~/org/TODO.org" "Read Later")
           "* TODO %?  :readlater:\nCREATED: %U")
          ("j" "Journal"
           entry (file+olp+datetree "~/org/journal.org.gpg")
           "* %? \nCREATED: %U\n%i\n%a"
           :empty-lines 1))))
#+END_SRC
** org-crypt

- [ ] TODO: Can I use multiple keys here?
- [ ] TODO: Create a shortcut for [[help:org-decrypt-entry][org-decrypt-entry]]
 
#+BEGIN_SRC emacs-lisp
(setq org-crypt-key "AA5A79D7AD584854")
#+END_SRC
* Keybindings

Helpful tip, use =SPC ?= to see a list of all available keybindings.

This [[https://rameezkhan.me/adding-keybindings-to-doom-emacs/][blog post]] helped me to figure out how to add new keybindings for doom-emacs. Also see [[https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el][evil-bindings.el]] for additional examples.

** Useful keybinding reminders

TODO: I'll probably want to sort this into categories eventually.

| Key       | What                                                               |
| =SPC ,=   | Switch to another buffer in the current project                    |
| =SPC b b= | ^                                                                  |
| =SPC <=   | Show/switch to all buffers in a session                            |
| =SPC b B= | ^                                                                  |
| =SPC b i= | Show interactive buffer picker, similar to ^                       |
| =SPC `=   | Switch to the last used buffer (=SPC b TAB= in spacemacs)          |
| =SPC b l= | ^                                                                  |
| =SPC o p= | Open treemacs in the project sidebar                               |
| =C-w w=   | Cycle through open windows                                         |
| =SPC 0=   | Go to the window to the left                                       |
| =SPC 1=   | Go to the window to the right                                      |
| =R=       | evil-multiedit - Select all matches at once                        |
| =M-d=     | evil-multiedit - start multicursor, keep pressing to expand search |

*** Convert Lists between ordered/numbere/unordered

If you have a list like this:

- item 1
- item 2
- item 3

You can change the - on the first item to a + or =1.= and then press =C-c C-c= and the rest of the list will automatically be updated to a numbered list.

*** Org outline navigation

For headings (and nested list items).  These work anywhere on the line:

| Key             | What                                                          |
|-----------------+--------------------------------------------------------------|
| =C-j=           | Next *sibling* heading (same level) — already bound          |
| =C-k=           | Previous *sibling* heading                                   |
| =g l=           | Move *into* the first child / nested item (=org-down-element=) |
| =g h=           | Move *up* to the parent (=org-up-element=)                   |
| =g j= / =g k=   | Next / previous element (also works on list items)           |
| =g H=           | Jump to the top-level heading                                 |
| =TAB= / =S-TAB= | Fold / unfold this item / the whole buffer                   |
| =C-c C-u=       | Up to parent heading                                          |

Because =org-use-speed-commands= is on (see [[#general][General]]), when point is on a
heading's stars (hit =0= to jump there) single keys navigate with no modifier — the
"easier than =g j/k=" option: =u= parent, =f= / =b= siblings, =n= / =p= next / prev
(=n= dives into the first child), =j= jump to any heading, =c= fold.


** Keybindings from Spacemacs

I keep trying to use these key shortcuts, so re-bind them to work in Doom.

See these links for some discussion around this:

- https://github.com/hlissner/doom-emacs/issues/2542
- https://github.com/hlissner/doom-emacs/issues/940
- https://github.com/chenyanming/spacemacs_module_for_doom
  - This module can be loaded to include a lot of spacemacs default functionality and keymaps, but I'd rather keep my config limited to what I actually need/want (on top of Doom)

I'm used to using =SPC N= to switch to window N, and use some other =SPC w ...= keys pretty often.
#+BEGIN_SRC emacs-lisp
;; TODO: I'm not sure how to go to a specific window, so this really just goes left and right for now
(map! :leader
      (:desc "Window left" "1" #'evil-window-left
       :desc "Window right" "2" #'evil-window-right))
(map! :leader
      (:prefix ("w" . "window")
               (:desc "Window left" "1" #'evil-window-left
                :desc "Window right" "2" #'evil-window-right
                :desc "evil-window-vsplit" "|" #'evil-window-vsplit
                :desc "evil-window-vsplit" "/" #'evil-window-vsplit)))
#+END_SRC

** Misc Keybindings

#+BEGIN_SRC emacs-lisp
;; macOS-style Cmd bindings (Emacs maps the Command key to Meta by default).  On Linux
;; these would clobber standard Alt bindings, so only enable them on macOS.
(when (eq system-type 'darwin)
  (map! "M-a" #'mark-whole-buffer   ; Select all
        "M-s" #'save-buffer         ; Save
        "M-v" #'consult-yank-pop))  ; Paste menu
#+END_SRC

** Navigation

Use Control + hjkl to move around windows in a frame.

#+BEGIN_SRC emacs-lisp
(map!
 :n "C-h" #'evil-window-left
 :n "C-j" #'evil-window-down
 :n "C-k" #'evil-window-up
 :n "C-l" #'evil-window-right
 )
#+END_SRC

The above only works in normal mode.  We have to add the same mapping for the treemacs mode.

#+BEGIN_SRC emacs-lisp
(map!
 (:map evil-treemacs-state-map
       "C-h" #'evil-window-left
       "C-l" #'evil-window-right)
 )
#+END_SRC

* Display
** Window Size and Position

This is from https://github.com/hlissner/doom-emacs/blob/develop/docs/api.org#center-emacs-initial-frame-with-a-fixed-size
#+BEGIN_SRC emacs-lisp
;; On startup, restore the last-used window size and position
(when-let (dims (doom-store-get 'last-frame-size))
  (cl-destructuring-bind ((left . top) width height fullscreen) dims
    (setq initial-frame-alist
          (append initial-frame-alist
                  `((left . ,left)
                    (top . ,top)
                    (width . ,width)
                    (height . ,height)
                    (fullscreen . ,fullscreen))))))

(defun save-frame-dimensions ()
  (doom-store-put 'last-frame-size
                  (list (frame-position)
                        (frame-width)
                        (frame-height)
                        (frame-parameter nil 'fullscreen))))

;; When we kill emacs, save the current window size and position
(add-hook 'kill-emacs-hook #'save-frame-dimensions)
#+END_SRC

I found this in the "better defaults" of https://tecosaur.github.io/emacs-config/config.html#better-defaults

#+begin_src emacs-lisp
(setq window-combination-resize t)
#+end_src

** Font and font sizing

TODO: Change font depending on OS?

#+BEGIN_SRC elisp
;; Add a small amount of extra space in between each line
(setq line-spacing 2)
#+END_SRC
** Theme

Lots of doom-specific themes available at https://github.com/hlissner/emacs-doom-themes
Screenshots available at: https://github.com/hlissner/emacs-doom-themes/tree/screenshots

Themes I like so far:

- doom-one - default theme, a little too dark for the comments
- doom-vibrant - almost the same as the default theme, but a little brighter
- doom-horizon - dark, more colorful than vibrant
- doom-tomorrow-night
- doom-material
- doom-dark+ - dark theme ported from VSCode

#+BEGIN_SRC emacs-lisp
;; Doom loads `doom-theme' for us, so just set it (an explicit load-theme double-loads).
(setq doom-theme 'doom-vibrant)
#+END_SRC

** Move to new split windows

#+BEGIN_SRC emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+END_SRC
** Indent guides

Saw a screenshot from https://old.reddit.com/r/emacs/comments/esgzjf/new_dark_theme_ported_from_vs_code_avaliable_now/ which included
https://github.com/DarthFennec/highlight-indent-guides

This package is installed/loaded from https://github.com/hlissner/doom-emacs/tree/develop/modules/ui/indent-guides

#+begin_src emacs-lisp
(setq highlight-indent-guides-responsive 'stack)
#+end_src
** Fix flickering

Since I upgraded to Big Sur, emacs seems to "flicker" a lot.  This should help prevent that.

Reference:

- https://github.com/hlissner/doom-emacs/issues/2989
- https://old.reddit.com/r/emacs/comments/ecctcp/how_to_debug_emacs_flickering_issue/
- https://old.reddit.com/r/emacs/comments/jx0uog/has_anyone_else_noticed_some_flickering_on_big_sur/
- https://old.reddit.com/r/emacs/comments/fbb4mm/how_to_debug_flickering/

#+begin_src emacs-lisp
;; The double-buffering flicker fix is macOS-specific (Big Sur+); on Linux/GTK it can make
;; flicker/tearing worse, so only apply it on macOS.
(when (eq system-type 'darwin)
  (add-to-list 'default-frame-alist '(inhibit-double-buffering . t)))
(setq display-line-numbers-type nil)
#+end_src
** Better window/frame titles

Borrowed from https://tecosaur.github.io/emacs-config/config.html#window-title

#+begin_src emacs-lisp
;; TODO: This didn't work for me
;; (setq frame-title-format
;;       '(""
;;         (:eval
;;          (if (s-contains-p org-roam-directory (or buffer-file-name ""))
;;              (replace-regexp-in-string
;;               ".*/[0-9]*-?" "☰ "
;;               (subst-char-in-string ?_ ?  buffer-file-name))
;;            "%b"))
;;         (:eval
;;          (let ((project-name (projectile-project-name)))
;;            (unless (string= "-" project-name)
;;              (format (if (buffer-modified-p)  " ◉ %s" "  ●  %s") project-name))))))
#+end_src

#+RESULTS:
|   | (:eval (if (s-contains-p org-roam-directory (or buffer-file-name )) (replace-regexp-in-string .*/[0-9]*-? ☰  (subst-char-in-string 95 32 buffer-file-name)) %b)) | (:eval (let ((project-name (projectile-project-name))) (unless (string= - project-name) (format (if (buffer-modified-p)  ◉ %s   ●  %s) project-name)))) |

* File management
** Send deleted files to trash
#+begin_src emacs-lisp
(setq delete-by-moving-to-trash t)
#+end_src
* Editing
** General Editing defaults

#+begin_src emacs-lisp
(global-subword-mode 1)
#+end_src
** Tabs vs Spaces

Use spaces instead of tabs by default, and set the default indent width to 2.  The =editorconfig= package/module should allow this to be overriden per project or repository.

- [ ] TODO:  Some languages like go want to use tabs by default, I should make sure that still happens.
- [ ] TODO:  =tab-width= only affects display, not actual number of spaces afaik

#+BEGIN_SRC elisp
(setq indent-tabs-mode nil
      tab-width 2)
#+END_SRC
** Unicode elipsis

From https://tecosaur.github.io/emacs-config/config.html

#+BEGIN_SRC emacs-lisp
(setq truncate-string-ellipsis "…")
#+END_SRC

** Markdown Mode

Enable things like wiki-style links so that I can more easily work with external editors/tools like [[https://obsidian.md/][Obsidian]].

#+BEGIN_SRC emacs-lisp
(setq markdown-enable-wiki-links t
      markdown-enable-math t
      markdown-fontify-code-blocks-natively t
      markdown-wiki-link-search-subdirectories t)
#+END_SRC

Enable ox-gfm as well

#+begin_src emacs-lisp :tangle packages.el
(package! ox-gfm)
#+end_src

#+begin_src emacs-lisp
(use-package! ox-gfm
  :after org)
#+end_src

** Terraform

Enables Terraform LSP support.  Install the language server following the instructions on https://github.com/hashicorp/terraform-ls/blob/main/docs/USAGE.md

#+begin_src emacs-lisp
;; lsp-mode ships a terraform-ls client that finds `terraform-ls' on PATH, so we just
;; enable lsp in terraform buffers when the server is actually installed.  This works on
;; Linux and both Intel and Apple-Silicon Homebrew without hardcoding a path.
(after! lsp-mode
  (when (executable-find "terraform-ls")
    (add-hook 'terraform-mode-hook #'lsp-deferred)))
#+end_src
** Corfu Completion

Doom now uses vertico + corfu for completion.  These are the corfu equivalents of my old
company settings (the original company block is in [[file:config.org_archive][config.org_archive]]).  The corfu module
already aborts completion when leaving evil insert state, so no abort hook is needed.

#+begin_src emacs-lisp
(after! corfu
  (setq corfu-auto t
        corfu-auto-delay 0.5
        corfu-auto-prefix 2))
#+end_src

* Version Control
** magit

See https://emacs.stackexchange.com/questions/32634/how-can-the-list-of-projects-used-by-projectile-be-manually-updated for an explanation.  This tells magit to look in ~/dev recursively.  My project structure is nested somewhat deep, but shouldn't be more than 4 nested directories.

#+BEGIN_SRC emacs-lisp
(after! magit
  ;; Set the directory where magit looks for repos in
  (setq magit-repository-directories '(("~/dev/" . 4))
        ;; Don't automatically save buffers when running magit
        magit-save-repository-buffers nil))
(after! projectile
  (when (require 'magit nil t)
    (mapc #'projectile-add-known-project
          (mapcar #'file-name-as-directory (magit-list-repos)))
    ;; Optionally write to persistent `projectile-known-projects-file'
    (projectile-save-known-projects)))
#+END_SRC

Show gravatars for commit authors
#+BEGIN_SRC emacs-lisp
(setq magit-revision-show-gravatars '("^Author:     " . "^Commit:     "))
#+END_SRC
** treemacs-magit
#+BEGIN_SRC emacs-lisp
(use-package! treemacs-magit
  :defer t
  :after (treemacs magit))
#+END_SRC
* Projectile

Use =SPC p D= to run discover projects in the search path.

This seems to only search one folder deep, so if you use a path of =~/dev= it detects =~/dev/proj1= but it will not detect something like =~/dev/clients/clientA/proj2=.

- [X] TODO: Can I use wildcards somehow?
- [ ] TODO: Discover projects in ~/dev/*/*/* (2 or 3 levels nested)
- [ ] TODO: my .gitignore isn't being honored anymore

#+BEGIN_SRC emacs-lisp
;; (setq projectile-project-search-path '("~/dev/" "~/dev/clients/"))
;; Found on https://github.com/bbatsov/projectile/issues/1500
;; TODO: This still isn't recursive more than one level
(when (file-directory-p "~/dev")
  (setq projectile-project-search-path (cddr (directory-files "~/dev" t))))
#+END_SRC

Projectile's indexing should be set to 'alien' by default, but hybrid still allows projectile to do some post-processing of the list of files returned inside of emacs.

#+begin_src emacs-lisp
(setq projectile-indexing-mode 'hybrid)
#+end_src

* SSH and GPG Agent

Attempt to source the env vars from keychain.
#+BEGIN_SRC elisp
;; Source ssh-agent/gpg env vars from the `keychain' CLI tool, if the package loaded.
(when (fboundp 'keychain-refresh-environment)
  (keychain-refresh-environment))
#+END_SRC

* Tramp

#+BEGIN_SRC emacs-lisp
;; Use /sshx because /ssh doesn't seem to work on bsd, and some of my
;; remote shells don't use sh/bash.  ssh/sshx should also be faster than scp
(setq tramp-default-method "sshx")
#+END_SRC
* Tags

I have a custom configuration for ctags stored in [[file:~/.ctags][~/.ctags]] that works with some additional languages like terraform, and excludes a lot of things like =node_modules= and =.terraform/modules= which causes the tags file to be too large.

#+BEGIN_SRC emacs-lisp
;; Use my default ctags configuration which excludes a lot of things we don't want
(setq projectile-tags-command (concat "ctags --options=" (expand-file-name "~/.ctags") " -Re -f \"%s\" %s \"%s\""))
#+END_SRC
* evil-snipe

#+BEGIN_SRC emacs-lisp
(use-package! evil-snipe
  :defer t
  :config
  ;; Alias [ and ] to all types of brackets
  ;; With this, I can use evil-snipe by pressing f and then [ and it will search for any of these types of brackets
  (push '(?\[ "[[{(]") evil-snipe-aliases)
  (push '(?\] "[]})]") evil-snipe-aliases)
  (setq evil-snipe-scope 'visible)
  (setq evil-snipe-repeat-scope 'buffer)
  (setq evil-snipe-spillover-scope 'whole-buffer))
#+END_SRC
* Backups and history

** Backups and auto-save

Doom already enables auto-save and disables lockfiles by default (lockfiles cause issues with Nextcloud), so all that's left here is to re-enable backups — doom/emacs has crashed enough times that I'd rather keep them.  Doom still configures [[help:backup-directory-alist][backup-directory-alist]] and friends even with backups disabled.

- TODO: I might want to change the backup location so that directories don't get cluttered if they go to the cwd.

#+BEGIN_SRC emacs-lisp
(setq make-backup-files t)
#+END_SRC
** Save place

Doom already enables =recentf= (with =recentf-max-saved-items 200=) and =savehist=, so I
don't configure those.  It sets up =saveplace= but doesn't actually turn on
=save-place-mode= (looks like an upstream bug), so enable it here to persist the cursor
position across sessions.

#+BEGIN_SRC emacs-lisp
(save-place-mode 1)
#+END_SRC
* Hydra Paste

From https://github.com/hlissner/doom-emacs/blob/develop/docs/api.org#create-a-paste-transient-state-to-cycle-through-kill-ring-on-paste

This lets me paste something and then cycle through the kill ring.

The doom-native way to do this is =SPC i y= which opens =yank-pop=.

#+BEGIN_SRC emacs-lisp
(defhydra hydra-paste (:color red
                       :hint nil)
  "\n[%s(length kill-ring-yank-pointer)/%s(length kill-ring)] \
 [_C-j_/_C-k_] cycles through yanked text, [_p_/_P_] pastes the same text \
 above or below. Anything else exits."
  ("C-j" evil-paste-pop)
  ("C-k" evil-paste-pop-next)
  ("p" evil-paste-after)
  ("P" evil-paste-before))

(map! :nv "p" #'hydra-paste/evil-paste-after
      :nv "P" #'hydra-paste/evil-paste-before)
#+END_SRC
* Avy

Search all open windows
#+BEGIN_SRC elisp
(setq avy-all-windows t)
#+END_SRC
* yasnippet

=:editor snippets= is enabled in =init.el=, we just need to enable yasnippet's global mode.

#+BEGIN_SRC emacs-lisp
(yas-global-mode 1)
#+END_SRC
